name: PHP Lint

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "**-*.php"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout du code
        uses: actions/checkout@v4
      
      - name: Lint php
        uses: firehed/lint-php-action@v1
        with:
          php-version: "8.2"